// Build @analitiq-ai/conversion-matrix from the engine's canonical artifact.
//
// The published grid is generated from cdk/cdk/type_map/conversion_matrix.json
// (itself generated from cdk/cdk/type_map/conversions.py and pinned by the
// engine's conformance test). This package never hand-edits the grid: it
// regenerates the typed data module on every build, so the published package
// cannot drift from the engine source.

import { execFileSync } from "node:child_process";
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parseVersion } from "./sync-contracts-to-s3.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const repoRoot = resolve(pkgRoot, "..", "..");
const sourceJson = join(repoRoot, "cdk", "cdk", "type_map", "conversion_matrix.json");

const raw = readFileSync(sourceJson, "utf8");
const { version, conversions: matrix } = JSON.parse(raw);
// The same version rule the publisher applies, imported rather than restated:
// a weaker check here would stamp an unpublishable version into matrixVersion,
// which consumers are told to assert on.
if (parseVersion(version) === null) {
  throw new Error(
    `conversion_matrix.json declares no usable version (got ${JSON.stringify(version)})`
  );
}
const families = matrix === null || typeof matrix !== "object" ? [] : Object.keys(matrix);
if (families.length === 0) {
  throw new Error("conversion_matrix.json carries no conversions grid");
}

// 1. Emit the typed data module. tsc checks the literal against ConversionMatrix,
//    so a malformed grid (missing cell field, unknown mode) fails the build.
//    matrixVersion is the artifact's own version, carried through so a consumer
//    can assert which policy it linked against. It is annotated `string`, not
//    left to infer the literal type — `matrixVersion === "1.1.0"` is a compile
//    error against a literal type, which is exactly the comparison it exists for.
const generated =
  "// AUTO-GENERATED by scripts/build.mjs from cdk/cdk/type_map/conversion_matrix.json.\n" +
  "// Do not edit by hand; regenerate with `npm run build`.\n" +
  'import type { ConversionMatrix } from "./types.js";\n\n' +
  `export const matrixVersion: string = ${JSON.stringify(version)};\n\n` +
  `export const arrowFamilies: readonly string[] = ${JSON.stringify(families)};\n\n` +
  `export const conversionMatrix: ConversionMatrix = ${JSON.stringify(matrix, null, 2)};\n`;
writeFileSync(join(pkgRoot, "src", "matrix.generated.ts"), generated);

// 2. Compile with the package-local tsc (no network, no global install).
const tsc = join(pkgRoot, "node_modules", ".bin", process.platform === "win32" ? "tsc.cmd" : "tsc");
execFileSync(tsc, ["-p", "tsconfig.json"], { cwd: pkgRoot, stdio: "inherit" });

// 3. Ship the raw document verbatim for non-TS consumers, byte-identical to source.
mkdirSync(join(pkgRoot, "dist"), { recursive: true });
const shippedJson = join(pkgRoot, "dist", "conversion_matrix.json");
copyFileSync(sourceJson, shippedJson);
if (Buffer.compare(readFileSync(shippedJson), readFileSync(sourceJson)) !== 0) {
  throw new Error("shipped conversion_matrix.json is not byte-identical to the engine source");
}

console.log(`built @analitiq-ai/conversion-matrix v${version} (${families.length} arrow families)`);
