"""The published ``contract-consumption`` manifest: contract fields the engine reads.

Every contract document the engine loads -- pipeline, stream, connection,
connector, endpoint -- is held as its typed ``analitiq.contracts`` model
from validation onwards, so every read is a typed attribute access and
"which contract fields does the engine use" is a static-analysis question.
The answer is rendered once per release into ``contract_consumption.json``
beside this module (by ``tools/contract_consumption.py``, from mypy's type
map) and shipped in the wheel, the way the Arrow type grammar and the
conversion matrix are. The contract repo pins it by version and sha256 and
fails a build when a field is neither read here nor declared authoring-only.

The manifest's contract, beside its shape: a field is claimed when the
engine reads it by any means it actually uses -- a typed attribute, a
``getattr`` over a registered table, a walk down a registered path table --
and a field no ``claims`` entry names is one no runtime path reads, not one
read in a way the census does not look for. ``opaque`` names the models a
consumer reads as a JSON grammar rather than field by field; ``transport``
is re-serialisation only, a document dumped for a reader that parses it
back as the same model.

The manifest is claims only: what the engine reads. Which unread fields are
defects, authoring metadata or validator-only is the contract repo's
decision, and stating it here would be a second copy of that decision.

This module is import-light on purpose (typing and pydantic only): the
loader runs wherever the CDK does, while the census that builds the file
needs mypy and stays a repository script.
"""

from __future__ import annotations

import json
import types
from collections.abc import Iterable
from pathlib import Path
from typing import Annotated, Any, Final, Union, get_args, get_origin

from pydantic import BaseModel

__all__ = [
    "CONTRACT_CONSUMPTION_PATH",
    "contract_models",
    "load_published_consumption",
    "model_name",
    "path_steps",
    "reachable_models",
]

#: The published artifact, committed beside this module. Generated by
#: ``tools/contract_consumption.py --write``; CI fails if the two drift.
CONTRACT_CONSUMPTION_PATH: Final[Path] = Path(__file__).with_name(
    "contract_consumption.json"
)


def load_published_consumption() -> dict[str, Any]:
    """Return the committed, published consumption manifest."""
    document: dict[str, Any] = json.loads(CONTRACT_CONSUMPTION_PATH.read_text())
    return document


def model_name(model: type[BaseModel]) -> str:
    """Return the name the manifest keys a contract model by: its import path."""
    return f"{model.__module__}.{model.__qualname__}"


def contract_models(annotation: Any) -> list[type[BaseModel]]:
    """Every pydantic model *annotation* can be, unions and Annotated unwrapped.

    The contract spells its request, pagination and replication branches as
    discriminated unions inside ``Annotated``, so "which models can this
    field hold" is a question about the annotation rather than about any
    one instance. Containers (``list[Column]``, ``dict[str, Param]``) are
    walked into, since a field holding a list of models is read through
    those models.
    """
    found: list[type[BaseModel]] = []
    pending: list[Any] = [annotation]
    while pending:
        node = pending.pop()
        origin = get_origin(node)
        if origin is Annotated:
            pending.append(get_args(node)[0])
        elif origin in (Union, types.UnionType):
            pending.extend(get_args(node))
        elif origin is not None:
            pending.extend(get_args(node))
        elif isinstance(node, type) and issubclass(node, BaseModel):
            if node not in found:
                found.append(node)
    return found


def reachable_models(roots: Iterable[Any]) -> dict[str, type[BaseModel]]:
    """Every model reachable from *roots* through field annotations, by name.

    *roots* are annotations (a model class, or a union alias such as
    ``Replication``); the closure follows each field's annotation, so a
    model the engine could only hold by way of a declared root is in the
    result and one it could not is not.
    """
    reachable: dict[str, type[BaseModel]] = {}
    pending: list[type[BaseModel]] = [
        model for root in roots for model in contract_models(root)
    ]
    while pending:
        model = pending.pop()
        name = model_name(model)
        if name in reachable:
            continue
        reachable[name] = model
        for field in model.model_fields.values():
            pending.extend(contract_models(field.annotation))
    return reachable


def path_steps(
    start: type[BaseModel], path: tuple[str, ...]
) -> list[tuple[type[BaseModel], str]]:
    """Every ``(model, field)`` step an attribute *path* walks from *start*.

    The walk follows every union member a field can hold, so a path that
    resolves through one branch of a discriminated union is stepped through
    that branch. A model declaring no field at a step contributes nothing
    there, which is the "nothing declared" a defaulted ``getattr`` walk
    answers; a walk that ends short returns fewer distinct keys than the
    path has.
    """
    steps: list[tuple[type[BaseModel], str]] = []
    nodes: list[type[BaseModel]] = [start]
    for key in path:
        next_nodes: list[type[BaseModel]] = []
        for node in nodes:
            if key not in node.model_fields:
                continue
            steps.append((node, key))
            next_nodes.extend(contract_models(node.model_fields[key].annotation))
        nodes = next_nodes
    return steps
