"""Render or check ``docker/requirements.txt``, generated from ``pyproject.toml``.

``docker/requirements.txt`` is what ``docker/Dockerfile`` installs into the
runtime image. It used to be hand-typed and drifted from ``pyproject.toml``
(a stale ``pyarrow`` floor shipped for a full release cycle). This script
generates it instead, via ``poetry export``, so the committed file can only
ever be a rendering of ``pyproject.toml`` / ``poetry.lock`` -- never a
second, independently-edited copy.

``poetry export`` (without ``--extras``) emits exactly the main, non-optional
dependency group -- everything still marked ``optional = true`` in
``pyproject.toml`` (currently just ``boto3``, gated behind the ``s3`` extra)
is left out, the same way ``poetry install`` would leave it out by default.

Requires the ``poetry-plugin-export`` plugin, which Poetry >=2.0 no longer
bundles.

Usage (from the repository root)::

    python tools/generate_docker_requirements.py --check   # CI: fail when stale
    python tools/generate_docker_requirements.py --write   # regenerate
"""

from __future__ import annotations

import argparse
import re
import subprocess  # nosec B404
import sys
from pathlib import Path
from typing import Final

_NAME_RE: Final[re.Pattern[str]] = re.compile(r"^[A-Za-z0-9._-]+")

REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[1]
REQUIREMENTS_PATH: Final[Path] = REPO_ROOT / "docker" / "requirements.txt"

HEADER: Final[str] = (
    "# Generated by `poetry export`, via"
    " tools/generate_docker_requirements.py --write.\n"
    "# Do not hand-edit -- regenerate instead. CI's docker-requirements job"
    " fails\n"
    "# the build if this drifts from pyproject.toml / poetry.lock.\n"
)


def render_requirements() -> str:
    """Return the runtime requirements file text, header plus a fresh export.

    Sorted by package name (case-insensitive), matching the
    ``requirements-txt-fixer`` pre-commit hook -- ``poetry export``'s own
    ordering doesn't agree with it (e.g. it emits ``aiohttp-retry`` before
    ``aiohttp``, since a raw-line sort puts ``-`` before the ``==`` on
    ``aiohttp``'s own line), so leaving the export as-is would make every
    commit fail lint until the hook resorted it.
    """
    result = subprocess.run(  # nosec B603 B607
        ["poetry", "export", "--without-hashes", "-f", "requirements.txt"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "poetry export failed (is poetry-plugin-export installed?):\n"
            f"{result.stderr}"
        )
    lines = [line for line in result.stdout.splitlines() if line]
    lines.sort(key=_sort_key)
    return HEADER + "\n".join(lines) + "\n"


def _sort_key(requirement_line: str) -> str:
    """Package name, lowercased -- the ``requirements-txt-fixer`` sort key."""
    match = _NAME_RE.match(requirement_line)
    if match is None:
        raise ValueError(f"not a requirement line: {requirement_line!r}")
    return match.group().lower()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--check", action="store_true", help="fail when the committed file is stale"
    )
    mode.add_argument(
        "--write", action="store_true", help="regenerate the committed file"
    )
    args = parser.parse_args(argv)

    rendered = render_requirements()

    if args.write:
        REQUIREMENTS_PATH.write_text(rendered)
        print(f"wrote {REQUIREMENTS_PATH}")
        return 0

    committed = REQUIREMENTS_PATH.read_text() if REQUIREMENTS_PATH.exists() else ""
    if committed == rendered:
        print(f"{REQUIREMENTS_PATH.name} is current")
        return 0

    print(
        f"{REQUIREMENTS_PATH.name} is stale; regenerate with "
        "`python tools/generate_docker_requirements.py --write`",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
