"""Pydantic models for type safety and validation."""

# New pipeline/stream models (PIPELINE.yaml, STREAM.yaml, STREAM_STATE.yaml specs)
from .pipeline import (
    BackoffStrategy,
    BatchingConfig,
    EngineRuntimeConfig,
    ErrorAction,
    ErrorCategoriesConfig,
    ErrorHandlingConfig,
    ExpressionConfig,
    ExpressionPolicy,
    FunctionCatalogConfig,
    LoggingConfig,
    PipelineConfig,
    PipelineConnectionsConfig,
    RetryConfig,
    RuntimeConfig,
    ScheduleConfig,
    ScheduleType,
)

from .stream import (
    Assignment,
    AssignmentTarget,
    AssignmentValue,
    ComparisonExpression,
    ConstExpression,
    ConstValue,
    DestinationBatchingConfig,
    DestinationConfig,
    ExpressionNode,
    ExpressionOp,
    FnExpression,
    GetExpression,
    IdempotencyKeyConfig,
    IfExpression,
    MappingConfig,
    PipeExpression,
    ReplicationConfig,
    ReplicationMethod,
    SourceConfig,
    StreamConfig,
    StreamRuntimeConfig,
    TargetType,
    ValidationConfig,
    ValidationRule,
    ValidationType,
    ValueKind,
    WriteMode,
    WriteModeConfig,
)

from .stream_state import (
    CheckpointState,
    CursorState,
    DeliveryState,
    DestinationCounters,
    DestinationDeliveryState,
    LastRunSummary,
    ReplicationState,
    RetryState,
    RunOutcome,
    StreamState,
    StreamStateIndex,
    StreamStatus,
)

# Engine models
from .engine import (
    EngineConfig,
    PipelineMetricsSnapshot,
    PipelineStagesConfig,
    StreamProcessingConfig,
    StreamStageConfig,
    TaskExecutionInfo,
)

# API models
from .api import (
    APIConfig,
    APIConnectionConfig,
    APIReadConfig,
    APIRequestParams,
    APIWriteConfig,
    EndpointConfig,
    FilterConfig,
    HostConfig,
    HTTPResponse,
    PaginationConfig,
    PaginationParams,
    RateLimitConfig,
    RecordBatch,
)

# Transformation models
from .transformations import (
    ComputedFieldConfig,
    FieldMappingConfig,
    MappingConfig as LegacyMappingConfig,
    TransformationConfig,
    TransformationResult,
    TransformationStats,
    TransformationType,
)

# Metrics models
from .metrics import PipelineMetrics

# Enriched config models (merged connection + endpoint + stream settings)
from .enriched import (
    BaseDestinationStreamConfig,
    BaseSourceStreamConfig,
    EnrichedAPIDestinationConfig,
    EnrichedAPISourceConfig,
    EnrichedDatabaseDestinationConfig,
    EnrichedDatabaseSourceConfig,
    EnrichedDestinationConfig,
    EnrichedSourceConfig,
)

# Legacy state models (for compatibility during transition)
from .state import (
    CursorField,
    HttpConditionals,
    PageState,
    PartitionCursor,
    PartitionState,
    PartitionStats,
    PipelineConfig as LegacyPipelineConfig,
    RunMetadata,
    ShardedStateIndex,
    DestinationConfig as LegacyDestinationConfig,
    ReplicationConfig as LegacyReplicationConfig,
    SourceConfig as LegacySourceConfig,
    StreamState as LegacyStreamState,
)

__all__ = [
    # Pipeline models
    "BackoffStrategy",
    "BatchingConfig",
    "EngineRuntimeConfig",
    "ErrorAction",
    "ErrorCategoriesConfig",
    "ErrorHandlingConfig",
    "ExpressionConfig",
    "ExpressionPolicy",
    "FunctionCatalogConfig",
    "LoggingConfig",
    "PipelineConfig",
    "PipelineConnectionsConfig",
    "RetryConfig",
    "RuntimeConfig",
    "ScheduleConfig",
    "ScheduleType",
    # Stream models
    "Assignment",
    "AssignmentTarget",
    "AssignmentValue",
    "ComparisonExpression",
    "ConstExpression",
    "ConstValue",
    "DestinationBatchingConfig",
    "DestinationConfig",
    "ExpressionNode",
    "ExpressionOp",
    "FnExpression",
    "GetExpression",
    "IdempotencyKeyConfig",
    "IfExpression",
    "MappingConfig",
    "PipeExpression",
    "ReplicationConfig",
    "ReplicationMethod",
    "SourceConfig",
    "StreamConfig",
    "StreamRuntimeConfig",
    "TargetType",
    "ValidationConfig",
    "ValidationRule",
    "ValidationType",
    "ValueKind",
    "WriteMode",
    "WriteModeConfig",
    # Stream state models
    "CheckpointState",
    "CursorState",
    "DeliveryState",
    "DestinationCounters",
    "DestinationDeliveryState",
    "LastRunSummary",
    "ReplicationState",
    "RetryState",
    "RunOutcome",
    "StreamState",
    "StreamStateIndex",
    "StreamStatus",
    # Engine models
    "EngineConfig",
    "PipelineMetricsSnapshot",
    "PipelineStagesConfig",
    "StreamProcessingConfig",
    "StreamStageConfig",
    "TaskExecutionInfo",
    # API models
    "APIConfig",
    "APIConnectionConfig",
    "APIReadConfig",
    "APIRequestParams",
    "APIWriteConfig",
    "EndpointConfig",
    "FilterConfig",
    "HostConfig",
    "HTTPResponse",
    "PaginationConfig",
    "PaginationParams",
    "RateLimitConfig",
    "RecordBatch",
    # Transformation models
    "ComputedFieldConfig",
    "FieldMappingConfig",
    "LegacyMappingConfig",
    "TransformationConfig",
    "TransformationResult",
    "TransformationStats",
    "TransformationType",
    # Metrics models
    "PipelineMetrics",
    # Enriched config models
    "BaseDestinationStreamConfig",
    "BaseSourceStreamConfig",
    "EnrichedAPIDestinationConfig",
    "EnrichedAPISourceConfig",
    "EnrichedDatabaseDestinationConfig",
    "EnrichedDatabaseSourceConfig",
    "EnrichedDestinationConfig",
    "EnrichedSourceConfig",
    # Legacy models (for compatibility)
    "CursorField",
    "HttpConditionals",
    "PageState",
    "PartitionCursor",
    "PartitionState",
    "PartitionStats",
    "RunMetadata",
    "ShardedStateIndex",
    "LegacyDestinationConfig",
    "LegacyPipelineConfig",
    "LegacyReplicationConfig",
    "LegacySourceConfig",
    "LegacyStreamState",
]
