"""Pydantic models for type safety and validation."""

# Pipeline models (mirrors k2m's PipelineConfig)
from .pipeline import (
    BatchingConfig,
    EngineConfig,
    EngineResourceConfig,
    ErrorCategoriesConfig,
    ErrorHandlingConfig,
    LoggingConfig,
    PipelineConfig,
    PipelineConnectionsConfig,
    RetryConfig,
    ScheduleConfig,
)

from .stream import (
    Assignment,
    AssignmentTarget,
    AssignmentValue,
    ComparisonExpression,
    ConstExpression,
    ConstValue,
    DestinationTypeMapping,
    DestinationBatchingConfig,
    DestinationConfig,
    ExpressionNode,
    ExpressionOp,
    FnExpression,
    GenericTypeMapping,
    GetExpression,
    IdempotencyKeyConfig,
    IfExpression,
    MappingConfig,
    PipeExpression,
    ReplicationConfig,
    ReplicationMethod,
    SourceConfig,
    StreamConfig,
    StreamEngineConfig,
    TargetType,
    ValidationConfig,
    ValidationRule,
    ValidationType,
    ValueKind,
    WriteMode,
    WriteModeConfig,
)

from .stream_state import (
    CheckpointState,
    CursorState,
    DeliveryState,
    DestinationCounters,
    DestinationDeliveryState,
    LastRunSummary,
    ReplicationState,
    RetryState,
    RunOutcome,
    StreamState,
    StreamStateIndex,
    StreamStatus,
)

# Engine models
from .engine import (
    PipelineMetricsSnapshot,
    PipelineStagesConfig,
    StreamProcessingConfig,
    StreamStageConfig,
    TaskExecutionInfo,
)

# API models
from .api import (
    APIConfig,
    APIConnectionConfig,
    APIReadConfig,
    APIRequestParams,
    APIWriteConfig,
    EndpointConfig,
    FilterConfig,
    HostConfig,
    HTTPResponse,
    PaginationConfig,
    PaginationParams,
    RateLimitConfig,
    RecordBatch,
)

# Transformation models
from .transformations import (
    ComputedFieldConfig,
    FieldMappingConfig,
    MappingConfig as LegacyMappingConfig,
    TransformationConfig,
    TransformationResult,
    TransformationStats,
    TransformationType,
)

# Metrics models
from .metrics import PipelineMetrics

# Enriched config models (merged connection + endpoint config)
from .enriched import (
    APIConnectionParameters,
    DatabaseConnectionParameters,
    EnrichedAPIConfig,
    EnrichedDatabaseConfig,
    EnrichedDestinationConfig,
    EnrichedSourceConfig,
)

from .state import (
    CursorField,
    HttpConditionals,
    PageState,
    StreamCursor,
    StreamStats,
    StreamState as SimpleStreamState,
    PipelineConfig as StatePipelineConfig,
    DestinationConfig as StateDestinationConfig,
    ReplicationConfig as StateReplicationConfig,
    SourceConfig as StateSourceConfig,
)

__all__ = [
    # Pipeline models
    "BatchingConfig",
    "EngineConfig",
    "EngineResourceConfig",
    "ErrorCategoriesConfig",
    "ErrorHandlingConfig",
    "LoggingConfig",
    "PipelineConfig",
    "PipelineConnectionsConfig",
    "RetryConfig",
    "ScheduleConfig",
    # Stream models
    "Assignment",
    "AssignmentTarget",
    "AssignmentValue",
    "ComparisonExpression",
    "ConstExpression",
    "ConstValue",
    "DestinationTypeMapping",
    "DestinationBatchingConfig",
    "DestinationConfig",
    "ExpressionNode",
    "ExpressionOp",
    "FnExpression",
    "GenericTypeMapping",
    "GetExpression",
    "IdempotencyKeyConfig",
    "IfExpression",
    "MappingConfig",
    "PipeExpression",
    "ReplicationConfig",
    "ReplicationMethod",
    "SourceConfig",
    "StreamConfig",
    "StreamEngineConfig",
    "TargetType",
    "ValidationConfig",
    "ValidationRule",
    "ValidationType",
    "ValueKind",
    "WriteMode",
    "WriteModeConfig",
    # Stream state models
    "CheckpointState",
    "CursorState",
    "DeliveryState",
    "DestinationCounters",
    "DestinationDeliveryState",
    "LastRunSummary",
    "ReplicationState",
    "RetryState",
    "RunOutcome",
    "StreamState",
    "StreamStateIndex",
    "StreamStatus",
    # Engine models
    "PipelineMetricsSnapshot",
    "PipelineStagesConfig",
    "StreamProcessingConfig",
    "StreamStageConfig",
    "TaskExecutionInfo",
    # API models
    "APIConfig",
    "APIConnectionConfig",
    "APIReadConfig",
    "APIRequestParams",
    "APIWriteConfig",
    "EndpointConfig",
    "FilterConfig",
    "HostConfig",
    "HTTPResponse",
    "PaginationConfig",
    "PaginationParams",
    "RateLimitConfig",
    "RecordBatch",
    # Transformation models
    "ComputedFieldConfig",
    "FieldMappingConfig",
    "LegacyMappingConfig",
    "TransformationConfig",
    "TransformationResult",
    "TransformationStats",
    "TransformationType",
    # Metrics models
    "PipelineMetrics",
    # Enriched config models
    "APIConnectionParameters",
    "DatabaseConnectionParameters",
    "EnrichedAPIConfig",
    "EnrichedDatabaseConfig",
    "EnrichedDestinationConfig",
    "EnrichedSourceConfig",
    # Stream-only state models
    "CursorField",
    "HttpConditionals",
    "PageState",
    "StreamCursor",
    "StreamStats",
    "SimpleStreamState",
    "StateDestinationConfig",
    "StatePipelineConfig",
    "StateReplicationConfig",
    "StateSourceConfig",
]
