"""Build, render and read the published consumption manifest."""

from __future__ import annotations

import asyncio
import json
from importlib import metadata
from pathlib import Path
from typing import Any, Final

from analitiq.contracts.endpoints import ApiEndpointDoc

from src.config.schema_validator import EndpointDocument

from .census import field_census
from .drive import drive_case
from .recording import ReadLedger, recording_document

__all__ = [
    "CONSUMPTION_MANIFEST_PATH",
    "CONSUMPTION_MANIFEST_VERSION",
    "CONTRACT_MODELS_DISTRIBUTION",
    "CORPUS_DIR",
    "RESOURCE_ROOTS",
    "build_consumption_manifest",
    "load_corpus",
    "load_published_manifest",
    "render_consumption_manifest",
]

# The manifest's own version, carried inside the artifact so any consumer
# can state which claim set it holds without asking the publisher.
#
# Bump it in the same commit as any change to what
# build_consumption_manifest() emits, across both axes: the claims (a
# field the engine starts or stops reading, a resource added) and the
# document's own shape (a top-level key). Minor when the change is purely
# additive for a consumer -- a newly claimed field only ever relaxes the
# gate; major when a claim is withdrawn or the shape changes, because a
# withdrawn claim can fail a build that passed. There is no patch tier: a
# consumer either reads the same claims or it does not. The publisher
# reads this version rather than assigning one, and refuses to republish
# changed content under an already-published version, so an unbumped
# change fails the sync run instead of overwriting an immutable object.
CONSUMPTION_MANIFEST_VERSION: Final[str] = "1.0.0"

#: The published contract models the claims are spelled against. Stated in
#: the artifact because a (model, field) pair only means something against
#: a known model tree -- a consumer pinned to a different revision has to
#: see that before it trusts a claim.
CONTRACT_MODELS_DISTRIBUTION: Final[str] = "analitiq-contract-models"

#: The resources the manifest covers, and the contract model each one's
#: document is rooted at. api-endpoint is the pilot; a further resource is
#: an entry here plus corpus cases, never a new mechanism.
RESOURCE_ROOTS: Final[dict[str, type[EndpointDocument]]] = {
    "api-endpoint": ApiEndpointDoc,
}

CORPUS_DIR: Final[Path] = Path(__file__).with_name("corpus")

# The published artifact, committed beside this module. Generated by
# build_consumption_manifest(); the pinning test fails if the two drift.
# Regenerate with:  python -m tools.consumption_manifest
CONSUMPTION_MANIFEST_PATH: Final[Path] = Path(__file__).with_name(
    "consumption_manifest.json"
)


def load_corpus(resource: str) -> list[dict[str, Any]]:
    """Every corpus case for *resource*, in a stable order.

    Sorted by filename so the drive order -- and therefore any ordering
    bug in it -- is reproducible rather than filesystem-dependent.
    """
    directory = CORPUS_DIR / resource
    cases = [json.loads(path.read_text()) for path in sorted(directory.glob("*.json"))]
    if not cases:
        raise FileNotFoundError(f"no corpus cases for {resource!r} under {directory}")
    return cases


def build_consumption_manifest() -> dict[str, Any]:
    """Materialise the manifest by driving the engine over the corpus.

    Each case's document is validated through the contract model it is
    rooted at -- a case the contract would reject could claim anything --
    then handed to the engine as the recording document a run would read.

    The ledger is intersected with the census before it is published, and
    that is not a formality. The resolver decides whether a node is an
    expression by asking it for ``ref``/``template``/``literal``, so it
    probes keys on nodes whose model has no such field. Those lookups are
    real, and they mean nothing: only a key the contract declares on that
    model is a claim about the contract.
    """
    resources: dict[str, Any] = {}
    for resource, root in RESOURCE_ROOTS.items():
        census = field_census(root)
        ledger = ReadLedger()
        for case in load_corpus(resource):
            document = recording_document(root.model_validate(case["document"]), ledger)
            asyncio.run(drive_case(case, document))
        claims = ledger.claims()
        consumed = {
            model: sorted(set(claims.get(model, ())) & set(fields))
            for model, fields in sorted(census.items())
        }
        resources[resource] = {
            "root_model": root.__name__,
            "consumed": {model: fields for model, fields in consumed.items() if fields},
        }
    return {
        "version": CONSUMPTION_MANIFEST_VERSION,
        "contract_models": metadata.version(CONTRACT_MODELS_DISTRIBUTION),
        "resources": resources,
    }


def render_consumption_manifest() -> str:
    """Canonical serialisation of the manifest, matching the committed artifact."""
    return json.dumps(build_consumption_manifest(), indent=2, sort_keys=True) + "\n"


def load_published_manifest() -> dict[str, Any]:
    """Return the committed, published manifest document."""
    document: dict[str, Any] = json.loads(CONSUMPTION_MANIFEST_PATH.read_text())
    return document
